
name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/maggadalka/new-repo:1.0 .
      - run: docker push ghcr.io/maggadalka/new-repo:1.0
      - run: ssh -o "StrictHostKeyChecking no" 'maggadalka-newrepo-hssyqux0x9h#CXlpaZjsB9oKMnfOPRs-h5bZsB9JEozm@maggadalka-newrepo-hssyqux0x9h.ssh.ws-eu106.gitpod.io' 'cd /workspace/new-repo && docker compose pull && docker compose up -d' 
